name: workflow_template
on: 
  push:
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz

jobs:
  bash_run:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: save to file
        run: | 
          echo "1235">test.txt 
          Get-Date -Format "dddd MM.dd.yyyy"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: test.txt

  bash_run_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brnaches: ["one", "two"]
    needs: ["bash_run"]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact  
      - name: check file
        run: |
          pwd
          ls
          cat test.txt
          echo ${{ matrix.brnaches }}
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Ref name
        run: echo ${{ github.ref_name }}
      - name: Ref
        run: echo ${{ github.ref }}
      - name: Test
        run: echo ${{ github.github_action }}
        
        
        

