name: workflow_template
on: 
  push:
    branches:
      - main
      - test
  workflow_dispatch:
    inputs:
      choice:
        type: choice
        description: Make a choice
        options:
        - foo
        - bar
        - baz

jobs:

  bash_run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: test other repo
        uses: actions/checkout@v3
        with:
          repository: MarcinCaryk/test_git_actions
          path: ./test_git_actions
          ref: v1
      - name: echo a string
        run: | 
          echo "Hello World"
      - name: save to file
        run: | 
          echo "1235">test.txt 
          Get-Date -Format "dddd MM.dd.yyyy"
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: test.txt

  bash_run_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
       include:
         - a: x
           b: "prod"
           c: "site-a"
         - a: y
           b: "dev"
           c: "site-b"
    needs: ["bash_run"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact 
      - name: echo a string
        run: | 
          echo "Hello World"
          python -V
          python .github/scripts/check_test_results.py -jxml test-results/test.xml
      - name: check file
        run: |
          pwd
          ls
          cat test.txt
          echo ${{ matrix.a }}
          echo ${{ matrix.b }}
          echo ${{ matrix.c }}
      - name: Output Run ID
        run: echo ${{ github.run_id }}
      - name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Ref name
        run: echo ${{ github.ref_name }}
      - name: Ref
        run: echo ${{ github.ref }}
      - name: Test
        run: echo ${{ github.github_action }}
        
        
        

