name: workflow_template
on: [push]

jobs:
  bash_run:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: save to file
        run: echo "1235">test.txt
      - name: check file
        run: cat test.txt
